### ISSUE TITLE
display "no tokens" when connection succesfull, but user dont own any token

### ISSUE THREAD

**Issue by oleggrib** [TokenScript/token-negotiator#778] opened 2023-07-31 18:23 UTC
Hello, TN UI displays same message when "no tokens" or "connect error", it shows "Load" in both cases. 
Its ambugiuous for user, better show different messages
<img width="737" alt="image" src="https://github.com/TokenScript/token-negotiator/assets/18176173/7653689e-c057-44b9-ab47-dc75db6f7d71">

**Comment by nicktaras** [comment] 2023-08-22 11:57
@oleggrib this was intended to allow the users to try again once it had failed.  Where the application at this time doesn’t find tokens that have become available e.g. a NFT transfer completed, or off chain Token generated and assigned to that user. 

We could as solution change this to;

- load for when it’s a first request
- retry for when it’s a further attempt to load the tokens

Please let me know your thoughts? @oleggrib

**Comment by oleggrib** [comment] 2023-09-07 13:06
@nicktaras  we can show "Load" when token not loaded yet.
"no tokens" when empty token list received

user can use "Refresh" button to reread tokens

**Comment by nicktaras** [comment] 2023-10-24 03:33
Hi @oleggrib,

Thanks for the feedback.

Version 3.2.0 introduces the following text configurations to allow you to flexibly manage the text, with regards to the scenario you have shared. 

- Auto Load tokens > "Load"
- User Clicks to load tokens > "Retry"
- When tokens are not found the notification utilises the text from 'noTokensFoundEvent'
- When tokens are found the following options can be utilised, 'balancesFoundEvent' and 'nftsFoundEvent'
- Off chain Tokens in this release utilise the 'nftsFoundEvent' text

````
uiOptions: {
          loadAction: "Load",
          repeatAction: "Retry",
          noTokensFoundEvent: 'No Tokens Found',
          balancesFoundEvent: 'Balance Found',
          nftsFoundEvent: 'Token(s) Found',
        },
````

**Closed by nicktaras** 2023-10-24 03:33 UTC
